[theme]
primaryColor = "#D45D75"
backgroundColor = "#F4F7FB"
secondaryBackgroundColor = "#FFFFFF"
textColor = "#20324A"
font = "sans serif"

[server]
headless = true

[browser]
gatherUsageStats = false
